### ISSUE TITLE
Cannot create an attribute from Sylius and populate data

### ISSUE THREAD

**Issue by romainruaud** [Elastic-Suite/gally-sylius-connector#2]
**Gally Platform version(s) affected**: 1.2.x

**Description**  

I cannot manage to create a new attribute into Sylius, populate some products with data, and have it synced with Gally.

**How to reproduce**  

Create an attribute in Sylius, with the "Select" type. I named it "Season" and created values like : Winter, Spring, Summer, Autumn.

I ran the gally:sync:structure command.

The "season" field appears as a "Select" in the Gally Back-Office, so it looks like it's okay.

When I go into editing a product in the Sylius back-office, I add "Season" and try to select the "Winter" value for this product.

When I hit save, I have this : 

`Gally\Rest\ApiException {#17715 ▼
  #responseBody: "{"type":"https:\/\/tools.ietf.org\/html\/rfc2616#section-10","title":"An error occurred","detail":"Bulk index operation failed 1 times in index gally_1_en_us_product_20231204_135233. Error (mapper_parsing_exception) : failed to parse field [season] of type [boolean] in document with id \u00277\u0027. Preview of field\u0027s value: \u00279a8bd9a2-92b2-11ee-952a-0242c0a80004\u0027. Failed doc ids sample : 7.","trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/srv\/api\/vendor\/gally\/gally-standard\/src\/Index\/Repository\/Document\/DocumentRepository.php","line":76,"args":[]},{"namespace":"Gally\\Index\\Repository\\Document","short_class":"DocumentRepository","class":"Gally\\Index\\Repository\\Document\\DocumentRepository","type":"-\u003E","function":"runBulk","file":"\/srv\/api\/vendor\/gally\/gally-standard\/src\/Index\/Repository\/Document\/DocumentRepository.php","line":38,"args":[["object","Gally\\Index\\Dto\\Bulk\\Request"],["boolean",false]]},{"namespace":"Gally\\Index\\Repository\\Document","short_class":"DocumentRepository","class":"Gally\\Index\\Repository\\Document\\DocumentRepository","type":"-\u003E","function":"index","file":"\/srv\/api\/vendor\/gally\/gally-standard\/src\/Index\/DataPersister\/DocumentDataPersister.php","line":42,"args":[["string","gally_1_en_us_product_20231204_135233"],["array",{"7":["string","{\u0022id\u0022:\u00227\u0022,\u0022sku\u0022:[\u0022Knitted_burgundy_winter_cap\u0022],\u0022name\u0022:[\u0022Knitted burgundy winter cap\u0022],\u0022image\u0022:[\u00227b\\\/aa\\\/a067211e5d043d3cb266cfe44f4a.jpg\u0022],\u0022price\u0022:[{\u0022price\u0022:91.51,\u0022original_price\u0022:91.51,\u0022group_id\u0022:0,\u0022is_discounted\u0022:false}],\u0022stock\u0022:{\u0022status\u0022:true,\u0022qty\u0022:9},\u0022category\u0022:[{\u0022id\u0022:\u0022caps\u0022,\u0022category_uid\u0022:\u0022caps\u0022,\u0022name\u0022:\u0022Caps\u0022,\u0022is_parent\u0022:true},{\u0022id\u0022:\u0022caps_with_pompons\u0022,\u0022category_uid\u0022:\u0022caps_with_pompons\u0022,\u0022name\u0022:\u0022With pompons\u0022,\u0022is_parent\u0022:false}],\u0022free_shipping\u0022:true,\u0022rating_avg\u0022:2,\u0022cap_brand\u0022:\u0022You are breathtaking\u0022,\u0022cap_collection\u0022:\u0022Sylius Winter 2019\u0022,\u0022cap_material\u0022:\u0022100% wool\u0022,\u0022season\u0022:[\u00229a8bd9a2-92b2-11ee-952a-0242c0a80004\u0022]}"]}]]},{"namespace":"Gally\\Index\\DataPersister","short_class":"DocumentDataPersister","class":"Gally\\Index\\DataPersister\\DocumentDataPersister","type":"-\u003E","function":"persist","file":"\/srv\/api\/vendor\/gally\/gally-standard\/src\/Product\/Decoration\/CategoryData\/SyncCategoryNameAfterBulkRest.php","line":40,"args":[["object","Gally\\Index\\Model\\IndexDocument"]]},{"namespace":"Gally\\Product\\Decoration\\CategoryData","short_class":"SyncCategoryNameAfterBulkRest","class":"Gally\\Product\\Decoration\\CategoryData\\SyncCategoryNameAfterBulkRest","type":"-\u003E","function":"persist","file":"\/srv\/api\/vendor\/gally\/gally-standard\/src\/Category\/Decoration\/SyncCategoryDataAfterBulkRest.php","line":44,"args":[["object","Gally\\Index\\Model\\IndexDocument"]]},{"namespace":"Gally\\Category\\Decoration","short_class":"SyncCategoryDataAfterBulkRest","class":"Gally\\Category\\Decoration\\SyncCategoryDataAfterBulkRest","type":"-\u003E","function":"persist","file":"\/srv\/api\/vendor\/api-platform\/core\/src\/DataPersister\/ChainDataPersister.php","line":59,"args":[["object","Gally\\Index\\Model\\IndexDocument"],["array",{"resource_class":["string","Gally\\Index\\Model\\IndexDocument"],"has_composite_identifier":["boolean",false],"identifiers":["array",{"indexName":["array",[["string","Gally\\Index\\Model\\IndexDocument"],["string","indexName"]]]}],"collection_operation_name":["string","post"],"receive":["boolean",true],"respond":["boolean",true],"persist":["boolean",true]}]]},{"namespace":"ApiPlatform\\Core\\DataPersister","short_class":"ChainDataPersister","class":"ApiPlatform\\Core\\DataPersister\\ChainDataPersister","type":"-\u003E","function":"persist","file":"\/srv\/api\/vendor\/api-platform\/core\/src\/Bridge\/Symfony\/Bundle\/DataPersister\/TraceableChainDataPersister.php","line":58,"args":[["object","Gally\\Index\\Model\\IndexDocument"],["array",{"resource_class":["string","Gally\\Index\\Model\\IndexDocument"],"has_composite_identifier":["boolean",false],"identifiers":["array",{"indexName":["array",[["string","Gally\\Index\\Model\\IndexDocument"],["string","indexName"]]]}],"collection_operation_name":["string","post"],"receive":["boolean",true],"respond":["boolean",true],"persist":["boolean",true]}]]},{"namespace":"ApiPlatform\\Core\\Bridge\\Symfony\\Bundle\\DataPersister","short_class":"TraceableChainDataPersister","class":"ApiPlatform\\Core\\Bridge\\Symfony\\Bundle\\DataPersister\\TraceableChainDataPersister","type":"-\u003E","function":"persist","file":"\/srv\/api\/vendor\/api-platform\/core\/src\/EventListener\/WriteListener.php","line":76,"args":[["object","Gally\\Index\\Model\\IndexDocument"],["array",{"resource_class":["string","Gally\\Index\\Model\\IndexDocument"],"has_composite_identifier":["boolean",false],"identifiers":["array",{"indexName":["array",[["string","Gally\\Index\\Model\\IndexDocument"],["string","indexName"]]]}],"collection_operation_name":["string","post"],"receive":["boolean",true],"respond":["boolean",true],"persist":["boolean",true]}]]},{"namespace":"ApiPlatform\\Core\\EventListener","short_class":"WriteListener","class":"ApiPlatform\\Core\\EventListener\\WriteListener","type":"-\u003E","function":"onKernelView","file":"\/srv\/api\/vendor\/symfony\/event-dispatcher\/Debug\/WrappedListener.php","line":111,"args":[["object","Symfony\\Component\\HttpKernel\\Event\\ViewEvent"],["string","kernel.view"],["object","Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher"]]},{"namespace":"Symfony\\Component\\EventDispatcher\\Debug","short_class":"WrappedListener","class":"Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener","type":"-\u003E","function":"__invoke","file":"\/srv\/api\/vendor\/symfony\/event-dispatcher\/EventDispatcher.php","line":230,"args":[["object","Symfony\\Component\\HttpKernel\\Event\\ViewEvent"],["string","kernel.view"],["object","Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher"]]},{"namespace":"Symfony\\Component\\EventDispatcher","short_class":"EventDispatcher","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"-\u003E","function":"callListeners","file":"\/srv\/api\/vendor\/symfony\/event-dispatcher\/EventDispatcher.php","line":59,"args":[["array",[["object","Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"],["object","Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"],["object","Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"],["object","Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"]]],["string","kernel.view"],["object","Symfony\\Component\\HttpKernel\\Event\\ViewEvent"]]},{"namespace":"Symfony\\Component\\EventDispatcher","short_class":"EventDispatcher","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"-\u003E","function":"dispatch","file":"\/srv\/api\/vendor\/symfony\/event-dispatcher\/Debug\/TraceableEventDispatcher.php","line":152,"args":[["object","Symfony\\Component\\HttpKernel\\Event\\ViewEvent"],["string","kernel.view"]]},{"namespace":"Symfony\\Component\\EventDispatcher\\Debug","short_class":"TraceableEventDispatcher","class":"Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher","type":"-\u003E","function":"dispatch","file":"\/srv\/api\/vendor\/symfony\/http-kernel\/HttpKernel.php","line":157,"args":[["object","Symfony\\Component\\HttpKernel\\Event\\ViewEvent"],["string","kernel.view"]]},{"namespace":"Symfony\\Component\\HttpKernel","short_class":"HttpKernel","class":"Symfony\\Component\\HttpKernel\\HttpKernel","type":"-\u003E","function":"handleRaw","file":"\/srv\/api\/vendor\/symfony\/http-kernel\/HttpKernel.php","line":74,"args":[["object","Symfony\\Component\\HttpFoundation\\Request"],["integer",1]]},{"namespace":"Symfony\\Component\\HttpKernel","short_class":"HttpKernel","class":"Symfony\\Component\\HttpKernel\\HttpKernel","type":"-\u003E","function":"handle","file":"\/srv\/api\/vendor\/symfony\/http-kernel\/Kernel.php","line":202,"args":[["object","Symfony\\Component\\HttpFoundation\\Request"],["integer",1],["boolean",true]]},{"namespace":"Symfony\\Component\\HttpKernel","short_class":"Kernel","class":"Symfony\\Component\\HttpKernel\\Kernel","type":"-\u003E","function":"handle","file":"\/srv\/api\/vendor\/symfony\/runtime\/Runner\/Symfony\/HttpKernelRunner.php","line":35,"args":[["object","Symfony\\Component\\HttpFoundation\\Request"]]},{"namespace":"Symfony\\Component\\Runtime\\Runner\\Symfony","short_class":"HttpKernelRunner","class":"Symfony\\Component\\Runtime\\Runner\\Symfony\\HttpKernelRunner","type":"-\u003E","function":"run","file":"\/srv\/api\/vendor\/autoload_runtime.php","line":29,"args":[]},{"namespace":"","short_class":"","class":"","type":"","function":"require_once","file":"\/srv\/api\/public\/index.php","line":3,"args":[["string","\/srv\/api\/vendor\/autoload_runtime.php"]]}]} ◀"
  #responseHeaders: array:19 [▶]
  #responseObject: null
}`

**Possible Solution**  

**Additional Context**  
!-- Optional: any other context about the problem: log messages, screenshots, etc. -->

**Comment by shochdoerfer** [comment]
If you tested this specifically with a Gally 1.2 endpoint, I guess it does not work because this PR is not yet merged: https://github.com/Elastic-Suite/gally-sylius-connector/pull/1

I'll check once I review the Pull Request. Thanks for raising the issue.

**Comment by romainruaud** [comment]
yeah, you're most probably right, it's unclear for me what's the _**exact**_ state of the environment I'm currently testing. 

So maybe I felt into this edge case.

We can wait for the #1 PR to be merged to check again.

**Comment by shochdoerfer** [comment]
Currently master is only compatible with Gally 1.1.

Maybe it would be a good idea to check if the version constraint matches when pinging the Gally server to see if the connection works. Can we somehow figure out the version of Gally server?

**Comment by shochdoerfer** [comment]
There seems to be a problem with how the select filter gets indexed for a product. Gally complains about some null values being sent. Will check & fix this.
