### ISSUE TITLE
Filters not working in front-office

### ISSUE THREAD

**Issue by romainruaud** [Elastic-Suite/gally-sylius-connector#3]
**Gally Platform version(s) affected**: 1.2.x

**Description**  

Filters are appearing in Front-Office but applying them has no effect.

**How to reproduce**  

Install Sylius and Gally, make most of the fields "filterable".

Check that they work with the Example Frontend app of Gally.

In Sylius, go to the "Cap" category and try to use one filter. The filter has no effect.

![image](https://github.com/Elastic-Suite/gally-sylius-connector/assets/15340849/6ed527c2-525b-4c50-ba13-6df3452d3b13)

![image](https://github.com/Elastic-Suite/gally-sylius-connector/assets/15340849/464ea839-46f5-4a7f-b7f2-77be19fed94e)

**Comment by shochdoerfer** [comment]
Cannot reproduce, the filtering works as expected for me. I am using the latest master version with Gally 1.2-x-dev for my testing.

![filters](https://github.com/Elastic-Suite/gally-sylius-connector/assets/596449/6867e489-5485-4453-ab58-af7574e9b7cb)

**Comment by shochdoerfer** [comment]
@Pigau can you check with Romain about the problem? Since I could not reproduce it locally, it might be fixed already (or some weird edge case).
