### ISSUE TITLE
UX : Filters should be rendered with Checkboxes in the front-office

### ISSUE THREAD

**Issue by romainruaud** [Elastic-Suite/gally-sylius-connector#6]
**Description**  

I dont think the design of the current version is really user friendly (cf #5 ).

On a general manner, I'd like to have the filters not being rendered with a Select box.

Having them rendered with checkboxes would be quite better.

![image](https://github.com/Elastic-Suite/gally-sylius-connector/assets/15340849/3f83a9f6-ccce-4e0c-94c8-b0191275a668)

![image](https://github.com/Elastic-Suite/gally-sylius-connector/assets/15340849/e9473a79-f780-46fa-a91a-5670cd3768f7)

**Comment by shochdoerfer** [comment]
I will check what's possible. Sylius seems to use the component in this specific way in Sylius Admin for their grids and I just reuse their code for the front office rendering. I'll check how to overwrite the template so that we can improve the rendering of the checkboxes.
